In [2]:
import numpy as np

Answer to Question 16:

In [9]:
A = np.array([[1,3],[2,2],[3,1]])
A.shape

(3, 2)

In [8]:
U, s, V = np.linalg.svd(A, full_matrices=False)
print(U, "\n", s, "\n", V)

[[-5.77350269e-01  7.07106781e-01]
 [-5.77350269e-01  3.06912759e-16]
 [-5.77350269e-01 -7.07106781e-01]] 
 [4.89897949 2.        ] 
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [12]:
s_p = np.diag(1/s)
print(s_p)
A_p = V @ s_p @ U.T
print(A_p)

[[0.20412415 0.        ]
 [0.         0.5       ]]
[[-0.16666667  0.08333333  0.33333333]
 [ 0.33333333  0.08333333 -0.16666667]]


In [15]:
print(A_p @ A)
print(A @ A_p)

[[ 1.00000000e+00  5.55111512e-17]
 [-2.49800181e-16  1.00000000e+00]]
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


Answer to Question 17:

In [17]:
A = np.array([[0,3,0],[2,0,0]])

In [19]:
U, s, V = np.linalg.svd(A, full_matrices=False)
print(U)
print(s)
print(V)

[[1. 0.]
 [0. 1.]]
[3. 2.]
[[0. 1. 0.]
 [1. 0. 0.]]


In [22]:
s_p = np.diag(1/s)
A_p = V.T @ s_p @ (U)
print(A_p)

[[0.         0.5       ]
 [0.33333333 0.        ]
 [0.         0.        ]]


Answer for Question 18:

In [26]:
A = np.array([[1,0,0],[1,0,0],[1,1,1]])
b = np.array([0,2,2])

In [27]:
U,s,V = np.linalg.svd(A, full_matrices=True)
# Create view of U with last columns 
U1 = U[:, :2]
print(U1)
V1 = V[:2,:]
print(V1)

# Create Sigma^{+}
S1 = np.diag(1.0/s[:-1])
print(S1)

[[-0.40824829 -0.57735027]
 [-0.40824829 -0.57735027]
 [-0.81649658  0.57735027]]
[[-0.81649658 -0.40824829 -0.40824829]
 [-0.57735027  0.57735027  0.57735027]]
[[0.5 0. ]
 [0.  1. ]]


In [30]:
x = np.transpose(V1).dot(S1.dot(U1.T).dot(b))
print(x)

[1.  0.5 0.5]
